// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcRequest.proto

package com.bytes.net.proto;

public final class ByteNetProto {
  private ByteNetProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RpcRequestOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string method = 1;
    /**
     * <code>required string method = 1;</code>
     */
    boolean hasMethod();
    /**
     * <code>required string method = 1;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>required string method = 1;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    // required bytes requestData = 2;
    /**
     * <code>required bytes requestData = 2;</code>
     */
    boolean hasRequestData();
    /**
     * <code>required bytes requestData = 2;</code>
     */
    com.google.protobuf.ByteString getRequestData();
  }
  /**
   * Protobuf type {@code net.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageLite
      implements RpcRequestOrBuilder {
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private RpcRequest(boolean noInit) {}

    private static final RpcRequest defaultInstance;
    public static RpcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              method_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              requestData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RpcRequest> PARSER =
        new com.google.protobuf.AbstractParser<RpcRequest>() {
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string method = 1;
    public static final int METHOD_FIELD_NUMBER = 1;
    private java.lang.Object method_;
    /**
     * <code>required string method = 1;</code>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string method = 1;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          method_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string method = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes requestData = 2;
    public static final int REQUESTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString requestData_;
    /**
     * <code>required bytes requestData = 2;</code>
     */
    public boolean hasRequestData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes requestData = 2;</code>
     */
    public com.google.protobuf.ByteString getRequestData() {
      return requestData_;
    }

    private void initFields() {
      method_ = "";
      requestData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMethod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMethodBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, requestData_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMethodBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, requestData_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bytes.net.proto.ByteNetProto.RpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code net.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bytes.net.proto.ByteNetProto.RpcRequest, Builder>
        implements com.bytes.net.proto.ByteNetProto.RpcRequestOrBuilder {
      // Construct using com.bytes.net.proto.ByteNetProto.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        method_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        requestData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bytes.net.proto.ByteNetProto.RpcRequest getDefaultInstanceForType() {
        return com.bytes.net.proto.ByteNetProto.RpcRequest.getDefaultInstance();
      }

      public com.bytes.net.proto.ByteNetProto.RpcRequest build() {
        com.bytes.net.proto.ByteNetProto.RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bytes.net.proto.ByteNetProto.RpcRequest buildPartial() {
        com.bytes.net.proto.ByteNetProto.RpcRequest result = new com.bytes.net.proto.ByteNetProto.RpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestData_ = requestData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bytes.net.proto.ByteNetProto.RpcRequest other) {
        if (other == com.bytes.net.proto.ByteNetProto.RpcRequest.getDefaultInstance()) return this;
        if (other.hasMethod()) {
          bitField0_ |= 0x00000001;
          method_ = other.method_;
          
        }
        if (other.hasRequestData()) {
          setRequestData(other.getRequestData());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMethod()) {
          
          return false;
        }
        if (!hasRequestData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bytes.net.proto.ByteNetProto.RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bytes.net.proto.ByteNetProto.RpcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string method = 1;
      private java.lang.Object method_ = "";
      /**
       * <code>required string method = 1;</code>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string method = 1;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string method = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        method_ = value;
        
        return this;
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = getDefaultInstance().getMethod();
        
        return this;
      }
      /**
       * <code>required string method = 1;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        method_ = value;
        
        return this;
      }

      // required bytes requestData = 2;
      private com.google.protobuf.ByteString requestData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes requestData = 2;</code>
       */
      public boolean hasRequestData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes requestData = 2;</code>
       */
      public com.google.protobuf.ByteString getRequestData() {
        return requestData_;
      }
      /**
       * <code>required bytes requestData = 2;</code>
       */
      public Builder setRequestData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        requestData_ = value;
        
        return this;
      }
      /**
       * <code>required bytes requestData = 2;</code>
       */
      public Builder clearRequestData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestData_ = getDefaultInstance().getRequestData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.RpcRequest)
    }

    static {
      defaultInstance = new RpcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.RpcRequest)
  }

  public interface RpcResponseOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required bytes responseData = 1;
    /**
     * <code>required bytes responseData = 1;</code>
     */
    boolean hasResponseData();
    /**
     * <code>required bytes responseData = 1;</code>
     */
    com.google.protobuf.ByteString getResponseData();
  }
  /**
   * Protobuf type {@code net.RpcResponse}
   */
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessageLite
      implements RpcResponseOrBuilder {
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private RpcResponse(boolean noInit) {}

    private static final RpcResponse defaultInstance;
    public static RpcResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RpcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private RpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              responseData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RpcResponse> PARSER =
        new com.google.protobuf.AbstractParser<RpcResponse>() {
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes responseData = 1;
    public static final int RESPONSEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString responseData_;
    /**
     * <code>required bytes responseData = 1;</code>
     */
    public boolean hasResponseData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes responseData = 1;</code>
     */
    public com.google.protobuf.ByteString getResponseData() {
      return responseData_;
    }

    private void initFields() {
      responseData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResponseData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, responseData_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, responseData_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.bytes.net.proto.ByteNetProto.RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bytes.net.proto.ByteNetProto.RpcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code net.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.bytes.net.proto.ByteNetProto.RpcResponse, Builder>
        implements com.bytes.net.proto.ByteNetProto.RpcResponseOrBuilder {
      // Construct using com.bytes.net.proto.ByteNetProto.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        responseData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.bytes.net.proto.ByteNetProto.RpcResponse getDefaultInstanceForType() {
        return com.bytes.net.proto.ByteNetProto.RpcResponse.getDefaultInstance();
      }

      public com.bytes.net.proto.ByteNetProto.RpcResponse build() {
        com.bytes.net.proto.ByteNetProto.RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.bytes.net.proto.ByteNetProto.RpcResponse buildPartial() {
        com.bytes.net.proto.ByteNetProto.RpcResponse result = new com.bytes.net.proto.ByteNetProto.RpcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseData_ = responseData_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.bytes.net.proto.ByteNetProto.RpcResponse other) {
        if (other == com.bytes.net.proto.ByteNetProto.RpcResponse.getDefaultInstance()) return this;
        if (other.hasResponseData()) {
          setResponseData(other.getResponseData());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResponseData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bytes.net.proto.ByteNetProto.RpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bytes.net.proto.ByteNetProto.RpcResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes responseData = 1;
      private com.google.protobuf.ByteString responseData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes responseData = 1;</code>
       */
      public boolean hasResponseData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes responseData = 1;</code>
       */
      public com.google.protobuf.ByteString getResponseData() {
        return responseData_;
      }
      /**
       * <code>required bytes responseData = 1;</code>
       */
      public Builder setResponseData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseData_ = value;
        
        return this;
      }
      /**
       * <code>required bytes responseData = 1;</code>
       */
      public Builder clearResponseData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseData_ = getDefaultInstance().getResponseData();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:net.RpcResponse)
    }

    static {
      defaultInstance = new RpcResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.RpcResponse)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
